# Generated by Django 4.0.3 on 2023-08-04 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pledge Class',
                'verbose_name_plural': 'Pledge Classes',
            },
        ),
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brother_number', models.IntegerField()),
                ('major', models.CharField(max_length=200)),
                ('eboard', models.BooleanField(default=False)),
                ('eboard_title', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField(blank=True)),
                ('grad_year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('headshot', models.URLField(blank=True, max_length=500, null=True)),
                ('pledge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brothers', to='brothers.pledgeclass')),
            ],
        ),
    ]
