# Generated by Django 4.0.3 on 2023-08-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EboardTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='brother',
            name='eboard_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brother', to='brothers.eboardtitle'),
        ),
    ]
