# Generated by Django 4.0.3 on 2023-08-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0002_eboardtitle_alter_brother_eboard_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eboardtitle',
            options={'verbose_name': 'Eboard Title', 'verbose_name_plural': 'Eboard Titles'},
        ),
        migrations.AlterField(
            model_name='brother',
            name='eboard_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brother', to='brothers.eboardtitle'),
        ),
    ]
