# Generated by Django 4.0.3 on 2023-08-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0003_alter_eboardtitle_options_alter_brother_eboard_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brother',
            name='eboard_title',
        ),
        migrations.AddField(
            model_name='brother',
            name='chair',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EboardTitle',
        ),
    ]
