# Generated by Django 4.0.3 on 2023-08-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0004_remove_brother_eboard_title_brother_chair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='chair',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
